export const COUNTRY_CODES = [
  { code: '+91',  name: 'India',               flag: '🇮🇳' },
  { code: '+1',   name: 'United States',        flag: '🇺🇸' },
  { code: '+44',  name: 'United Kingdom',       flag: '🇬🇧' },
  { code: '+971', name: 'UAE',                  flag: '🇦🇪' },
  { code: '+966', name: 'Saudi Arabia',         flag: '🇸🇦' },
  { code: '+974', name: 'Qatar',                flag: '🇶🇦' },
  { code: '+973', name: 'Bahrain',              flag: '🇧🇭' },
  { code: '+968', name: 'Oman',                 flag: '🇴🇲' },
  { code: '+965', name: 'Kuwait',               flag: '🇰🇼' },
  { code: '+61',  name: 'Australia',            flag: '🇦🇺' },
  { code: '+1',   name: 'Canada',               flag: '🇨🇦' },
  { code: '+64',  name: 'New Zealand',          flag: '🇳🇿' },
  { code: '+65',  name: 'Singapore',            flag: '🇸🇬' },
  { code: '+60',  name: 'Malaysia',             flag: '🇲🇾' },
  { code: '+66',  name: 'Thailand',             flag: '🇹🇭' },
  { code: '+63',  name: 'Philippines',          flag: '🇵🇭' },
  { code: '+62',  name: 'Indonesia',            flag: '🇮🇩' },
  { code: '+84',  name: 'Vietnam',              flag: '🇻🇳' },
  { code: '+86',  name: 'China',                flag: '🇨🇳' },
  { code: '+81',  name: 'Japan',                flag: '🇯🇵' },
  { code: '+82',  name: 'South Korea',          flag: '🇰🇷' },
  { code: '+852', name: 'Hong Kong',            flag: '🇭🇰' },
  { code: '+886', name: 'Taiwan',               flag: '🇹🇼' },
  { code: '+92',  name: 'Pakistan',             flag: '🇵🇰' },
  { code: '+880', name: 'Bangladesh',           flag: '🇧🇩' },
  { code: '+94',  name: 'Sri Lanka',            flag: '🇱🇰' },
  { code: '+977', name: 'Nepal',                flag: '🇳🇵' },
  { code: '+960', name: 'Maldives',             flag: '🇲🇻' },
  { code: '+93',  name: 'Afghanistan',          flag: '🇦🇫' },
  { code: '+98',  name: 'Iran',                 flag: '🇮🇷' },
  { code: '+964', name: 'Iraq',                 flag: '🇮🇶' },
  { code: '+972', name: 'Israel',               flag: '🇮🇱' },
  { code: '+90',  name: 'Turkey',               flag: '🇹🇷' },
  { code: '+20',  name: 'Egypt',                flag: '🇪🇬' },
  { code: '+27',  name: 'South Africa',         flag: '🇿🇦' },
  { code: '+234', name: 'Nigeria',              flag: '🇳🇬' },
  { code: '+254', name: 'Kenya',                flag: '🇰🇪' },
  { code: '+233', name: 'Ghana',                flag: '🇬🇭' },
  { code: '+256', name: 'Uganda',               flag: '🇺🇬' },
  { code: '+255', name: 'Tanzania',             flag: '🇹🇿' },
  { code: '+251', name: 'Ethiopia',             flag: '🇪🇹' },
  { code: '+212', name: 'Morocco',              flag: '🇲🇦' },
  { code: '+49',  name: 'Germany',              flag: '🇩🇪' },
  { code: '+33',  name: 'France',               flag: '🇫🇷' },
  { code: '+39',  name: 'Italy',                flag: '🇮🇹' },
  { code: '+34',  name: 'Spain',                flag: '🇪🇸' },
  { code: '+351', name: 'Portugal',             flag: '🇵🇹' },
  { code: '+31',  name: 'Netherlands',          flag: '🇳🇱' },
  { code: '+32',  name: 'Belgium',              flag: '🇧🇪' },
  { code: '+41',  name: 'Switzerland',          flag: '🇨🇭' },
  { code: '+43',  name: 'Austria',              flag: '🇦🇹' },
  { code: '+46',  name: 'Sweden',               flag: '🇸🇪' },
  { code: '+47',  name: 'Norway',               flag: '🇳🇴' },
  { code: '+45',  name: 'Denmark',              flag: '🇩🇰' },
  { code: '+358', name: 'Finland',              flag: '🇫🇮' },
  { code: '+354', name: 'Iceland',              flag: '🇮🇸' },
  { code: '+353', name: 'Ireland',              flag: '🇮🇪' },
  { code: '+48',  name: 'Poland',               flag: '🇵🇱' },
  { code: '+420', name: 'Czech Republic',       flag: '🇨🇿' },
  { code: '+36',  name: 'Hungary',              flag: '🇭🇺' },
  { code: '+40',  name: 'Romania',              flag: '🇷🇴' },
  { code: '+30',  name: 'Greece',               flag: '🇬🇷' },
  { code: '+380', name: 'Ukraine',              flag: '🇺🇦' },
  { code: '+7',   name: 'Russia',               flag: '🇷🇺' },
  { code: '+55',  name: 'Brazil',               flag: '🇧🇷' },
  { code: '+54',  name: 'Argentina',            flag: '🇦🇷' },
  { code: '+52',  name: 'Mexico',               flag: '🇲🇽' },
  { code: '+57',  name: 'Colombia',             flag: '🇨🇴' },
  { code: '+56',  name: 'Chile',                flag: '🇨🇱' },
  { code: '+51',  name: 'Peru',                 flag: '🇵🇪' },
]

export const DEFAULT_COUNTRY = COUNTRY_CODES[0]

export function findCountryByCode(dialCode) {
  return COUNTRY_CODES.find((c) => c.code === dialCode) ?? DEFAULT_COUNTRY
}
